services:
  service:
    build:
      context: ..
      dockerfile: ./04-circuit-breaker/Dockerfile.service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - dependency
  dependency:
    build:
      context: ..
      dockerfile: ./04-circuit-breaker/Dockerfile.dependency
    ports:
      - "8081:8080"
    env_file:
      - .env
  yandex_tank:
    image: "yandex/yandex-tank"
    volumes:
      - ./load.yaml:/var/loadtest/load.yaml
      - ../token.txt:/var/loadtest/token.txt
    depends_on:
      - service
      - dependency
